---
title: 'Homework #2'
author: "Your Name"
date: "2/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cars and mileage

In this homework we will use the `mpg` data set, you can access the data by loading the package `ggplot2` into your R session by executing the command 
`library(ggplot2)`. The `mpg` data includes information about fuel economy of popular car models
for the years 1999 and 2008 as collected by the US Environmental Protection Agency.


Most exercises are from the ggplot2 book section 2.2.1. You might find it helpful for working on the homework to read through this section.

1. Download the RMarkdown file with these homework instructions to use as a template for your work.
Make sure to replace "Your Name" in the YAML with your name.
1.  List five functions that you could use to get more information about the
mpg dataset.
2. Using the `ggplot2` package create a scatterplot of `hwy` and `cty` and describe the relationship. Why are there so few points visible? Use a geom that helps reduce the amount of overplotting in the scatterplot.
3. Apart from the US, most countries use fuel consumption (fuel consumed
over fixed distance) rather than fuel economy (distance traveled with fixed
amount of fuel). How could you convert `cty` and `hwy` into the European
standard of liter/100 km? Introduce corresponding variables into the `mpg` data.
4.  Are cars in 2008 more fuel efficient than cars in 1999? Expand on your answer in (2) for a visual approach to this question. Note: you are not asked to find numeric answers. Instead, interpret plots. 
6. Use the `ggplot2` package to create  side-by-side boxplots of `cty` by `class`. Describe the relationship in 2-3 sentences. 
Change the label for the y-axis to 'city miles per gallon' (see ```?ylab```).  


Note: your submission is supposed to be fully reproducible, i.e. the TA and I will 'knit' your submission in RStudio. Including the link to the image is the tricky part here. Make sure that you don't use any file structure that depends on your computing environment.


For the submission: submit your solution in an R Markdown file and (just for insurance) submit the corresponding html (or Word) file with it. 
