---
title: "note"
author: "Will Ju"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(classdata)
library(ggplot2)
```

# Your Turn

<https://ds202-at-isu.github.io/materials/02_r-intro/03_r-graphics.html#9>

```{r}
head(fbiwide)


ggplot(fbiwide, aes(x = year,
                    y = motor_vehicle_theft)) +
  geom_line() +
  facet_wrap(~ state)
```

-   with `log` scale

```{r}
ggplot(fbiwide, aes(x = year,
                    y = log(motor_vehicle_theft))) +
  geom_line() +
  facet_wrap(~ state)
```

-   `scales` parameter in `facet_wrap`

```{r}
ggplot(fbiwide, aes(x = year,
                    y = motor_vehicle_theft)) +
  geom_line() +
  facet_wrap(~ state, scales = "free_y") 
```

# `facet_grid` and `facet_wrap`

```{r}
library(dplyr)
df1 <- data.frame(
  x = seq(-1, 1, 0.1),
  type = 'up'
)
df1$y <- df1$x
df2 <- data.frame(
  x = seq(-1, 1, 0.1),
  type = 'down'
)
df2$y <- -df2$x
df <- rbind(df1, df2)
df <- df %>% mutate(
  sign = if_else(y >= 0, 'positive', 'negative')
)
```

```{r}
ggplot(df, aes(x = x, y = y)) +
  geom_point() +
  facet_grid(type ~ sign)
```

```{r}
ggplot(df, aes(x = x, y = y)) +
  geom_point() +
  facet_grid(. ~ sign)
```

# boxplot

-   visualize relationship between one numeric variable and one categorical variable

```{r}
ggplot(fbi, aes(x = type, y = log(count))) +
  geom_boxplot() +
  coord_flip()
```

-   `coord_flip()` for better label readability

# Your Turn

<https://ds202-at-isu.github.io/materials/02_r-intro/03_r-graphics.html#14>

```{r}
ggplot(fbiwide, 
       aes(x = reorder(state, log(robbery), median),
           y = log(robbery))) +
  geom_boxplot() +
  coord_flip()
```

```{r}
fbiwide$robbery_rate <- 
  fbiwide$robbery / fbiwide$population
ggplot(fbiwide, 
       aes(x = reorder(state, robbery_rate, median),
           y = robbery_rate)) +
  geom_boxplot() +
  coord_flip()
```

# histogram

-   super wide bin

```{r}
ggplot(fbiwide, aes(x = motor_vehicle_theft)) + 
  geom_histogram(binwidth = 1000000)
```

-   super thin bin

```{r}
ggplot(fbiwide, aes(x = motor_vehicle_theft)) + 
  geom_histogram(binwidth = 10)
```

-   finding an appropriate bin width is crucial

```{r}
ggplot(fbiwide, aes(x = motor_vehicle_theft)) + 
  geom_histogram(binwidth = 5000)
```

-   if `binwidth` is not provided

```{r}
ggplot(fbiwide, aes(x = motor_vehicle_theft)) + 
  geom_histogram()
```

# barchart

```{r}
ggplot(fbi, aes(x = type)) + 
  geom_bar(aes(weight= count)) +
  coord_flip()
```

```{r}
bar_data <- data.frame(
  type = c('a', 'a', 'a', 'b', 'b', 'c'),
  value = sample(10, 6)
)

# default
ggplot(bar_data, aes(x = type)) +
  geom_bar()

# using `weight` for accumulation
ggplot(bar_data, aes(x = type)) +
  geom_bar(aes(weight = value))
```

# Your turn

<https://ds202-at-isu.github.io/materials/02_r-intro/03_r-graphics.html#20>

```{r}
ggplot(fbi, aes(x = violent_crime)) +
  geom_bar(aes(weight = count)) +
  facet_wrap( ~ type)
```

```{r}
ggplot(fbi, aes(x = violent_crime,
                fill = type)) +
  geom_bar(aes(weight = count))
```

```{r}
ggplot(fbi, aes(x = count)) +
  geom_histogram() +
  facet_wrap(~type, scales = "free_y")
```
